### ISSUE TITLE
something about surface normal calc

### ISSUE THREAD

**Issue by tornadomeet** [s-gupta/rgbdutils#1]
hi,  
i just read the code of computing suface normal from one depth image,https://github.com/s-gupta/rgbdutils/blob/master/computeNormals.m, there is some formula in it, so what's the theory? and can i found some materials about this?(i have read the papers you write, but with no more details)  thanks.

**Comment by ghost** [comment]
hi, i also read the code, do you solve the problem?  i use 4 parameter model, but slow.

**Comment by ghost** [comment]
@tornadomeet

**Comment by JamesMcCullochDickens** [comment]
@tornadomeet check out linear least squares for plane fitting, should give you an idea.

http://www.ilikebigbits.com/2015_03_04_plane_from_points.html

**Comment by tornadomeet** [comment]
thanks @JamesMcCullochDickens
