### ISSUE TITLE
Build imagestack failed: recipe for target 'joint_bilateral_mex' failed

### ISSUE THREAD

**Issue by hojat-kaveh** [s-gupta/rgbdutils#2]
Hi all
I'm trying to build the Matlab wrapper according to help:
`cd eccv14-code/rgbdutils/imagestack/`
`make all -j 16`
`cd ../../../`

and I get this error:
`/bin/sh: 1: /usr/local/MATLAB/R2012b: Permission denied`
`Makefile.common:113: recipe for target 'joint_bilateral_mex' failed`
`make: *** [joint_bilateral_mex] Error 126`

I've also tried making with `sudo` and using both Matlab R2016b and R2012b, all of these return the same error. I'm using Ubuntu 16.04 and gcc 5.4.0 as the compiler for Matlab.
can you tell what is causing this error?

**Comment by hojat-kaveh** [comment]
ok. looks like the issue is resolved somehow! after a `make clean` and restart I built the Matlab wrapper (with Matlab 2016b) successfully!

**Comment by asifraza151** [comment]
@hojat-kaveh I face the same problem as you, can you explain the solutions?

**Comment by asifraza151** [comment]
/bin/mex matlab/joint_bilateral_mex.cpp CXX="g++" CXXFLAGS="\$CXXFLAGS  -Iinclude/ -fPIC " CXXLIBS="\$CXXLIBS " -output matlab/joint_bilateral_mex.mexa64
/bin/sh: 1: /bin/mex: not found
Makefile:113: recipe for target 'joint_bilateral_mex' failed
make: *** [joint_bilateral_mex] Error 127
